# Generated by Django 5.2.10 on 2026-03-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprecheckout',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprecheckout',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcompleted',
            name='user_pre_checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='application.userprecheckout'),
        ),
    ]
