# Generated by Codex on 2026-06-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("application", "0002_userprecheckout_message_userprecheckout_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprecheckout",
            name="referral_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_pre_checkouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
